### ISSUE TITLE
Grafana

### ISSUE THREAD

**Issue by benthehorn** [shrestaz/TechNews-LSD#2]
Your grafana dashboard seems to be down, there's no data in the rows..

**Comment by shrestaz** [comment]
We moved or system to a new droplet yesterday so we forgot to update the Prometheus config file. Will update in a couple of hours 😴💤.
Thanks Ben

**Comment by shrestaz** [comment]
Hey Ben,
I've updated the configuration with our new IP address so Grafana should be working.
[Link to Grafana](http://207.154.245.251:4000/dashboard/db/nodeapi-monitoring?refresh=5s&orgId=1&from=1511842201689&to=1511863801689)

- Manish
